smart.lang['en'] = {
	'do-you-know-the-answer': 'Do you know the answer?',
	'do-you-know-the-image-this-belongs-to': 'Do you know the image this belongs to',
	'can-you-recall-whats-on-the-picture': 'Can you recall what\'s on the picture?',
	'can-you-recall-what-you-are-hearing': 'Can you recall what you are hearing?',
	'can-you-recall-what-you-are-watching': 'Can you recall what you are watching?',
	'do-you-know-how-to-spell-this': 'Do you know how to spell this?',
	'do-you-know-how-to-spell-the-answer': 'Do you know how to spell the answer?',
	'an-error-occured-while-trying-to-prepare-your-study-data-please-try-reloading': 'An error occured while trying to prepare your study data. Please try reloading.',
	'loading': 'loading',
	'study-item': 'Study Item',
	'sentences': 'Sentences',
	'extra-info': 'Extra Info',
	'quiz-practice': 'Quiz Practice',
	'yes': 'Yes',
	'maybe': 'Maybe',
	'no': 'No',
	'next': 'Next',
	'review-again': 'Review again',
	'none-of-the-above': 'None of the above',
	'start': 'Start',
	'new': 'New',
	'created-by': 'Created by',
	'sentence-source': 'Sentence Source'
}