smart.lang['ja'] = {
	'do-you-know-the-answer': '答えをわかりますか？',
	'do-you-know-the-image-this-belongs-to': 'Do you know the image this belongs to',
	'can-you-recall-whats-on-the-picture': 'Can you recall what\'s on the picture?',
	'can-you-recall-what-you-are-hearing': 'Can you recall what you are hearing?',
	'can-you-recall-what-you-are-watching': 'Can you recall what you are watching?',
	'do-you-know-how-to-spell-this': 'Do you know how to spell this?',
	'do-you-know-how-to-spell-the-answer': 'Do you know how to spell the answer?',
	'an-error-occured-while-trying-to-prepare-your-study-data-please-try-reloading': 'An error occured while trying to prepare your study data. Please try reloading.',
	'loading': 'loading',
	'study-item': 'アイテム',
	'sentences': '例文',
	'extra-info': '追加情報',
	'quiz-practice': 'クイズ',
	'yes': 'はい',
	'maybe': '多分',
	'no': 'いいえ',
	'next': '次',
	'review-again': '学習へ',
	'none-of-the-above': 'その他',
	'start': 'スタート',
	'new': '新',
	'created-by': 'Created by',
	'sentence-source': 'Sentence Source'
}