smart.lang['de'] = {
	'do-you-know-the-answer': 'Kennst du die richtige Antwort?',
	'do-you-know-the-image-this-belongs-to': 'Kennst du das passende Bild?',
	'can-you-recall-whats-on-the-picture': 'Was ist auf dem Bild dargestellt?',
	'can-you-recall-what-you-are-hearing': 'Was hörst du gerade?',
	'can-you-recall-what-you-are-watching': 'Was siehst du hier?',
	'do-you-know-how-to-spell-this': 'Weisst du wie man das schreibt?',
	'do-you-know-how-to-spell-the-answer': 'Kannst du die Antwort schreiben?',
	'an-error-occured-while-trying-to-prepare-your-study-data-please-try-reloading': 'An error occured while trying to prepare your study data. Please try reloading.',
	'loading': 'lade..',
	'study-item': 'Lernen',
	'sentences': 'Sätze',
	'extra-info': 'Mehr Infos',
	'quiz-practice': 'Quiz Übungen',
	'yes': 'Ja',
	'maybe': 'Vielleicht',
	'no': 'Nein',
	'next': 'Weiter',
	'review-again': 'Nochmal üben',
	'none-of-the-above': 'Keins von oben',
	'start': 'Start',
	'new': 'Neu',
	'created-by': 'Erstellt von',
	'sentence-source': 'Quelle'
}